[package]
name = "calibrate"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
anyhow = "1.0.57"
serial = { path = "../serial" }
sensor-fusion = { path = "../sensor-fusion" }
glam = "0.20.5"