[build]
target = "avr-specs/avr-atmega2560.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 1000000"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]
